[MODFISTO-363] - Language deleted
folio-org/raml pull request #148
Opened 2022-12-30 13:55 UTC by Dmitriy-Butramyou

## Purpose
_Describe the purpose of the pull request. Include background information if necessary._

## Approach
_How does this change fulfill the purpose?_

#### TODOS and Open Questions
- [ ] Use GitHub checklists. When solved, check the box and explain the answer.

## Learning
_Describe the research stage. Add links to blog posts, patterns, libraries or addons used to solve this problem._

## Screenshots
_Let's see those sweet visuals!_

2022-12-30 19:59 UTC, adamdickmeiss requested changes
Refer to issue FOLIO project, not a module like mod-finane-storage.

In reality this is FOLIO-3351 not fully done.

2022-12-31 15:38 UTC, julianladisch requested changes
The title "[MODFISTO-363] - Language deleted" is wrong, it should be "[FOLIO-3351] - Language deleted" or a follow-up FOLIO issue of FOLIO-3351.
This pull request blocks MODFISTO-363 because MODFISTO-363 bumps the raml submodule, but they are separate issues:
https://issues.folio.org/browse/MODFISTO-363
https://issues.folio.org/browse/FOLIO-3351

2023-01-20 14:12 UTC, julianladisch approved these changes
Looks good, thanks!

2023-01-23 07:31 UTC, SerhiiNosko approved these changes

2023-01-23 07:42 UTC, Abdulkhakimov approved these changes

2023-01-23 14:19 UTC, adamdickmeiss approved these changes

2023-01-23 14:21 UTC, merged